# Generated by Django 5.1.7 on 2025-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('_password', models.CharField(editable=False, max_length=16, verbose_name='数据存储密码')),
                ('nickname', models.CharField(max_length=10, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, max_length=10, verbose_name='性别')),
                ('introduction', models.TextField(max_length=3222, verbose_name='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sport_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
