# Generated by Django 5.1.7 on 2025-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='默认用户', max_length=10, verbose_name='昵称'),
        ),
    ]
