# Generated by Django 5.1.7 on 2025-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_password',
            field=models.TextField(editable=False, max_length=25555, verbose_name='数据存储密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='这个人很懒，什么都没有留下。', max_length=200, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='默认用户', max_length=32, verbose_name='昵称'),
        ),
    ]
