# Generated by Django 5.1.7 on 2025-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user__password_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_time',
            field=models.IntegerField(default=0, verbose_name='活跃时间'),
        ),
    ]
