# Generated by Django 5.1.7 on 2025-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_active_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_password',
            field=models.TextField(max_length=25555, verbose_name='数据存储密码'),
        ),
    ]
