# Generated by Django 5.1.7 on 2025-04-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='sportuser',
        ),
    ]
