# Generated by Django 5.1.7 on 2025-04-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[('1', '男'), ('0', '女')], default='1', verbose_name='性别'),
        ),
    ]
