# Generated by Django 5.1.7 on 2025-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('0', '女')], default='1', max_length=2, verbose_name='性别'),
        ),
    ]
