# Generated by Django 5.1.7 on 2025-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/daoge.png', upload_to='avatar/', verbose_name='头像'),
        ),
    ]
