# Generated by Django 5.1.7 on 2025-04-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='content',
            field=models.TextField(max_length=200, verbose_name='文章内容'),
        ),
    ]
