# Generated by Django 5.1.7 on 2025-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_chatcontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
