# Generated by Django 5.1.7 on 2025-04-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chatcontent_like'),
        ('user_app', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user_app.user', verbose_name='用户'),
        ),
    ]
